### ISSUE TITLE
Where do we go for help?

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/manubot#29]
Can you add something to suggest where we go to make inquiries about how to use manubot? Not really "issues" like bug reports or feature requests, but if you want other sorts of inquiries as issues that is possible too. The alternative would be a mailing list, discussion forum, or Gitter (not @agitter) somewhere.

**Comment by dhimmel** [comment]
> if you want other sorts of inquiries as issues that is possible too

Currently, we use issues for everything and it's encouraged to post issues asking for help, as needed.

I'd consider Gitter. @agitter what do you think? Where should we document how to ask for help? Perhpas in `USAGE.md`?

FYI, most of your questions at this time are probably more related to [`manubot-rootstock`](https://github.com/greenelab/manubot-rootstock) than this repo. But I see how it's not clear to most users where to ask for help.

**Comment by agitter** [comment]
I haven't adopted Gitter (not entirely due to the naming collision) so issues work well as part of my existing workflow.  My first choice would be to more clearly recommend issues for everything in manubot and manubot-rootstock.  That could go in the usage document or readme to make it easy to find.  But I would also join another medium if we want to move the discussion.

**Comment by michaelmhoffman** [comment]
I think if you want people to get all sorts of support through issues, that's fine, just better if it were clear that's how you want it. Some of us were trained to never send anything that wasn't a bug or feature request through a bug trackers. 😄
