### ISSUE TITLE
manubot and manubot-rootstock READMEs should have suggested citations

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/manubot#59]
It should be easy to find what the suggested citation for each of these is right at the top. See https://genomedata.hoffmanlab.org/ for an example

**Comment by slochower** [comment]
Oh, you mean citations for Manubot and Manubot-rootstock. I was looking at your link for two minutes, thinking there was a citation type there that we need to support.

**Comment by michaelmhoffman** [comment]
Yes. I think it is likely that the citation would be a version of https://greenelab.github.io/meta-review/ for both though

**Comment by agitter** [comment]
@dhimmel this makes sense to me.  Should we add the meta review citation to both readmes?

**Comment by dhimmel** [comment]
There are two separate issues:

1. Manubot documentation supplying the citation for Manubot. https://greenelab.github.io/meta-review/ is currently the best citation, in terms of citing a manuscript describing the project.
2. Individual manuscripts built with Manubot can include their citation in their README and in their manuscript text.

Regarding 1, I think we could add the suggested Meta Review citation to [`USAGE.md`](https://github.com/greenelab/manubot-rootstock/blob/master/USAGE.md) and the greenelab/manubot [README](https://github.com/greenelab/manubot/blob/master/README.md). I don't necessarily want to add it to the Rootstock README because I don't want their to be any confusion where someone intends to cite a manuscript built with manubot but instead cites the Manubot.
