### ISSUE TITLE
Passing PMCID to PMID citation parser

### ISSUE THREAD

**Issue by agitter** [greenelab/manubot#71]
I wanted to use Manubot to cite [PMCID PMC6063279 ](https://www.ncbi.nlm.nih.gov/pubmed/?term=PMC6063279) and instead received a citation for [PMID 6063279](https://www.ncbi.nlm.nih.gov/pubmed/?term=6063279).  I had accidentally written
```
manubot cite pmid:PMC6063279
```

Apparently the Entrez eutils takes the PMCID, strips `PMC`, and then returns the [XML](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=PMC6063279&rettype=full) for that numeric PMID.  This seems like an error on the part of eutils.  Do we want to try to prevent this type of user error?  Or should we instead leave the Manubot behavior but notify the eutils maintainers?

**Comment by agitter** [comment]
> Yes, we could check the pubmed ID for being all numeric.

What would be more user-friendly?
- Throw an error if someone uses `pmid:PMC6063279`
- Check whether the non-numeric PMID starts with `PMC` and redirect the citation to `get_pmc_citeproc`

**Comment by dhimmel** [comment]
We could warn and redirect, but I'm in favor of throwing the error such that the user is required to fix it. We want manubot manuscripts to adhere to good standards, especially say for future projects that analyze citation practices.

I'm thinking we need better validation of all identifier types. If we know that a certain ID must adhere to a given format, we should do those checks for the user and provide good error messages, rather than the potentially more confusing error message provided by our retrieval functions.

**Comment by agitter** [comment]
I'm supportive of throwing an error if the error message is informative.  We could potentially make detailed error messages that help catch the most common errors.  Something like
> `PMC6063279 is not a valid PubMed Identifier.  You can cite this PubMed Centeral Identifier using pmcid:PMC6063279?`
